name: CI

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run allure:tests
        continue-on-error: true

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: allure-results

  reporting:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Allure command-line tool
        run: npm install -g allure-commandline --save-dev

      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: allure-report

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Publish report
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./allure-report

