name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ${{ github.workspace }}

env:
  wd: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run allure:tests
        continue-on-error: true

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: allure-results

    outputs:
      test-results-path: ${{ steps.upload.outputs.artifactPath }}

  reporting:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Allure command-line tool
        run: npm install -g allure-commandline --save-dev

      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: allure-results

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Publish report
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

